name: test
on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  change:
    runs-on: ubuntu-latest

    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with: 
        base: main
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
        
  backend:
    needs: change
    if: ${{ needs.chage.outputs.backend == 'true' }}

    uses: ./.github/workflows/backend.yml

  frontend:
    needs: change
    if: ${{ needs.chage.outputs.frontend == 'true' }}

    uses: ./.github/workflows/frontend.yml

  